# Feature
config: Hail\Config

alias:
  class|to: Hail\AliasLoader
  arguments: ["@config->get:alias"]

i18n: Hail\I18n\I18n

event:
  class|to: Hail\Event\EventManager
  to:
    - Hail\Event\Psr\EventManagerInterface

auth: Hail\Auth\Manager
browser:
  class|to: Hail\Http\Browser
  arguments: ["@config->get:browser"]

cache: "@cache.simple"

cache.simple:
  factory: Hail\Factory\Cache::simple
  to:
    - Hail\Cache\Simple\CacheInterface
    - Psr\SimpleCache\CacheInterface

cache.pool:
  factory: Hail\Factory\Cache::pool
  to:
    - Hail\Cache\CacheItemPoolInterface
    - Psr\Cache\CacheItemPoolInterface

db: Hail\Factory\Database::pdo
cdb:
  factory: Hail\Factory\Database::cache
  arguments: ["@db", "@cache"]
  to:
    - Hail\Database\Cache\CachedDBInterface

router:
  class|to: Hail\Router
  arguments: ["@config->get:route"]

storage: Hail\Factory\Storage::mount

template:
  class|to: Hail\Template\Engine
  arguments: ["@config->get:template"]

image:
  class|to: Hail\Image\ImageManager
  arguments: ["@config->get:image"]

serializer: Hail\Serialize\Serializer
json: "@serializer->json"

# Tools
arrays: Hail\Util\Arrays
crypto: Hail\Util\Crypto
debugger: Hail\Debugger\Debugger
logger:
  factory: Hail\Debugger\Debugger::getLogger
  to:
    - Psr\Log\LoggerInterface
generators: Hail\Util\Generators
inflector: Hail\Util\Inflector
strings: Hail\Util\Strings
validator: Hail\Util\Validator

# Application
app:
  class|to: Hail\Application
  arguments: ["@container"]

console:
  class|to: Hail\Console\Application
  arguments: ["@config->get:console"]

request:
  class|to: Hail\Http\Request
  arguments: ["@app"]

response:
  class|to: Hail\Http\Response
  arguments: ["@app", "@request"]

service:
  class: Hail\Util\ObjectFactory
  arguments: [App\Service, "@container"]

lib:
  class: Hail\Util\ObjectFactory
  arguments: [App\Library, "@container"]

model:
  class: Hail\Util\ObjectFactory
  arguments: [App\Model, "@container"]

session:
  class|to: Hail\Session\Session
  arguments: ["@config->get:cookie", "@request", "@response"]
  calls:
    setHandler: ["@config->get:session"]

httpServer: "@swoole->http"

# Swoole
swoole: Hail\Swoole\Server

# Middleware
Hail\Http\Middleware\ErrorHandler: []
Hail\Http\Middleware\MethodOverride: []
Hail\Http\Middleware\BasePath:
  arguments: ["@config->get:app.basePath"]
Hail\Http\Middleware\ClientIp:
  calls:
    proxy: ["@config->get:app.proxies"]
Hail\Http\Middleware\Cors:
  arguments: ["@config->get:cors"]
Hail\Http\Middleware\Payload: []
Hail\Http\Middleware\ScriptPath: []
Hail\Http\Middleware\TrailingSlash: []
Hail\Http\Middleware\ContentType: []
Hail\Http\Middleware\ContentEncoding: []
Hail\Http\Middleware\ContentLanguage:
  arguments: ["@config->get:app.languages"]

# Hail Framework middleware
Hail\Http\Middleware\Session:
  arguments: ["@session"]
Hail\Http\Middleware\I18n:
  arguments: ["@container"]
Hail\Http\Middleware\Route:
  arguments: ["@router"]
Hail\Http\Middleware\Handler:
  arguments: ["@app"]
